datasource:
  user: root
  password: liangqinghai
  host: 127.0.0.1
  port: 3306
  database: test

jwt:
  secret: helloworld

log:
  fileName: admin.log
  level: debug

server:
  host: 0.0.0.0
  port: 8888